### ISSUE TITLE
chapter 4 summary doesn't match chapter 4

### ISSUE THREAD

**Issue by oren** [elibenporat/learn-to-code-rust-baseball#4]
I might have made a mistake. when I look at the content of 'All The Code From This Chapter' it doesn't match what was discussed in chapter 4. maybe it's half of chapter 5? I am not sure (:

**Comment by elibenporat** [comment]
Fixed with 8fb1274e03d3015ffbd1d48097b00718d6b5e037.

Thanks for catching this. It actually included an old version of Chapter 5. I also moved it to Chapter 5, since it was redundant in Ch. 4.
